x = int (input("Enter first number: "))
y = int (input("Enter second number: "))
print("First  Number :",x)
print("Second Number :",y)
print("First  Number in binary :",bin(x).replace("0b",""))
print("Second Number in binary :",bin(y).replace("0b",""))
a1 = bin(x & y).replace("0b","")
print("Bitwise AND :",a1)
print("in Decimal  :",int(a1,2))
a2 = bin(x | y).replace("0b","")
print("Bitwise OR :",a2)
print("in Decimal  :",int(a2,2))
a3 = bin(x ^ y).replace("0b","")
print("Bitwise XOR :",a3)
print("in Decimal  :",int(a3,2))
a4 = bin(x << 2).replace("0b","")
print("Left Shift by 2 :",a4)
print("in Decimal  :",int(a4,2))
a5 = bin(x >> 2).replace("0b","")
print("Right Shift by 2 :",a5)
print("in Decimal  :",int(a5,2))